import type { BracketPick } from '@/lib/bracket/types';

export const BRACKET_PICKS: BracketPick[] = [
  {
    player: 'Beck',
    champion: 'Arizona',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'SFLA',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: 'Duke',
      east_s16_2: 'UConn',
      east_e8_1: 'UConn',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'Texas A&M',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Illinois',
      south_e8_1: 'Illinois',

      west_r64_1: 'Arizona',
      west_r64_2: 'Villanova',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Wisconsin',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'MIAOH',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Iowa St.',

      f4_1: 'UConn',
      f4_2: 'Arizona',
      champ_1: 'Arizona',
    },
  },
  {
    player: 'Doko',
    champion: 'Duke',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'TCU',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'Louisville',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: 'Kansas',
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: 'Duke',
      east_s16_2: 'UConn',
      east_e8_1: 'Duke',

      south_r64_1: 'Florida',
      south_r64_2: 'Clemson',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Florida',

      west_r64_1: 'Arizona',
      west_r64_2: 'Utah St.',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Missouri',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Georgia',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'Tennessee',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Michigan',

      f4_1: 'Duke',
      f4_2: 'Arizona',
      champ_1: 'Duke',
    },
  },
  {
    player: 'Friske',
    champion: 'Michigan',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Cal Baptist',
      east_r64_5: 'Louisville',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: "St. John's",
      east_s16_2: 'MICHST',
      east_e8_1: 'MICHST',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Troy',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Florida',

      west_r64_1: 'Arizona',
      west_r64_2: 'Villanova',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'Tennessee',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Virginia',
      midwest_e8_1: 'Michigan',

      f4_1: 'Florida',
      f4_2: 'Michigan',
      champ_1: 'Michigan',
    },
  },
  {
    player: 'Gunee',
    champion: 'Arizona',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'TCU',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'Louisville',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: 'Kansas',
      east_r32_3: 'MICHST',
      east_r32_4: 'UCLA',
      east_s16_1: 'Kansas',
      east_s16_2: 'MICHST',
      east_e8_1: 'MICHST',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Florida',

      west_r64_1: 'Arizona',
      west_r64_2: 'Villanova',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Georgia',
      midwest_r64_3: 'Akron',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'MIAOH',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Michigan',

      f4_1: 'Florida',
      f4_2: 'Arizona',
      champ_1: 'Arizona',
    },
  },
  {
    player: 'Hata',
    champion: 'Arizona',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'SFLA',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCF',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: "St. John's",
      east_s16_2: 'UConn',
      east_e8_1: 'UConn',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'VCU',
      south_r64_6: 'Illinois',
      south_r64_7: 'Texas A&M',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Houston',

      west_r64_1: 'Arizona',
      west_r64_2: 'Utah St.',
      west_r64_3: 'High Point',
      west_r64_4: 'Hawaii',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Missouri',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'High Point',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'MIAOH',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Texas Tech',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Michigan',

      f4_1: 'UConn',
      f4_2: 'Arizona',
      champ_1: 'Arizona',
    },
  },
  {
    player: 'Kuaya',
    champion: 'Duke',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'Louisville',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCF',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: 'Kansas',
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: 'Duke',
      east_s16_2: 'UConn',
      east_e8_1: 'Duke',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Nebraska',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Houston',

      west_r64_1: 'Arizona',
      west_r64_2: 'Utah St.',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Missouri',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Gonzaga',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Georgia',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'Tennessee',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Michigan',

      f4_1: 'Duke',
      f4_2: 'Arizona',
      champ_1: 'Duke',
    },
  },
  {
    player: 'Manlai',
    champion: 'Houston',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'SFLA',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'SFLA',
      east_r32_4: 'UConn',
      east_s16_1: "St. John's",
      east_s16_2: 'UConn',
      east_e8_1: 'UConn',

      south_r64_1: 'Florida',
      south_r64_2: 'Clemson',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'VCU',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Houston',

      west_r64_1: 'Arizona',
      west_r64_2: 'Utah St.',
      west_r64_3: 'High Point',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'BYU',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'BYU',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'MIAOH',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Santa Clara',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Alabama',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Alabama',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Iowa St.',

      f4_1: 'Houston',
      f4_2: 'Arizona',
      champ_1: 'Houston',
    },
  },
  {
    player: 'Temmy',
    champion: 'Duke',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'TCU',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'SFLA',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'MICHST',
      east_r32_4: 'UConn',
      east_s16_1: 'Duke',
      east_s16_2: 'UConn',
      east_e8_1: 'Duke',

      south_r64_1: 'Florida',
      south_r64_2: 'Iowa',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'MARYCA',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Houston',

      west_r64_1: 'Arizona',
      west_r64_2: 'Utah St.',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Purdue',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'Tennessee',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Santa Clara',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Texas Tech',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Virginia',
      midwest_e8_1: 'Virginia',

      f4_1: 'Duke',
      f4_2: 'Arizona',
      champ_1: 'Duke',
    },
  },
  {
    player: 'TG',
    champion: 'Arizona',
    picks: {
      east_r64_1: 'Duke',
      east_r64_2: 'Ohio St.',
      east_r64_3: "St. John's",
      east_r64_4: 'Kansas',
      east_r64_5: 'Louisville',
      east_r64_6: 'MICHST',
      east_r64_7: 'UCLA',
      east_r64_8: 'UConn',
      east_r32_1: 'Duke',
      east_r32_2: "St. John's",
      east_r32_3: 'MICHST',
      east_r32_4: 'UCLA',
      east_s16_1: "St. John's",
      east_s16_2: 'MICHST',
      east_e8_1: "St. John's",

      south_r64_1: 'Florida',
      south_r64_2: 'Clemson',
      south_r64_3: 'Vanderbilt',
      south_r64_4: 'Nebraska',
      south_r64_5: 'N. Carolina',
      south_r64_6: 'Illinois',
      south_r64_7: 'Texas A&M',
      south_r64_8: 'Houston',
      south_r32_1: 'Florida',
      south_r32_2: 'Vanderbilt',
      south_r32_3: 'Illinois',
      south_r32_4: 'Houston',
      south_s16_1: 'Florida',
      south_s16_2: 'Houston',
      south_e8_1: 'Houston',

      west_r64_1: 'Arizona',
      west_r64_2: 'Villanova',
      west_r64_3: 'Wisconsin',
      west_r64_4: 'Arkansas',
      west_r64_5: 'BYU',
      west_r64_6: 'Gonzaga',
      west_r64_7: 'Miami',
      west_r64_8: 'Purdue',
      west_r32_1: 'Arizona',
      west_r32_2: 'Arkansas',
      west_r32_3: 'Gonzaga',
      west_r32_4: 'Purdue',
      west_s16_1: 'Arizona',
      west_s16_2: 'Gonzaga',
      west_e8_1: 'Arizona',

      midwest_r64_1: 'Michigan',
      midwest_r64_2: 'Saint Louis',
      midwest_r64_3: 'Texas Tech',
      midwest_r64_4: 'Alabama',
      midwest_r64_5: 'Tennessee',
      midwest_r64_6: 'Virginia',
      midwest_r64_7: 'Kentucky',
      midwest_r64_8: 'Iowa St.',
      midwest_r32_1: 'Michigan',
      midwest_r32_2: 'Texas Tech',
      midwest_r32_3: 'Virginia',
      midwest_r32_4: 'Iowa St.',
      midwest_s16_1: 'Michigan',
      midwest_s16_2: 'Iowa St.',
      midwest_e8_1: 'Michigan',

      f4_1: 'Houston',
      f4_2: 'Arizona',
      champ_1: 'Arizona',
    },
  },
];

export const PLAYER_FINALS = {
  Beck: 'UConn vs Arizona',
  Doko: 'Duke vs Arizona',
  Friske: 'Florida vs Michigan',
  Gunee: 'Florida vs Arizona',
  Hata: 'UConn vs Arizona',
  Kuaya: 'Duke vs Arizona',
  Manlai: 'Houston vs Arizona',
  Temmy: 'Duke vs Arizona',
  TG: 'Houston vs Arizona',
} as const;